apiVersion: v1
kind: Service
metadata:
  name: your-value
  namespace: your-namespace
spec:
  type: NodePort
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 7890       # Target internal native TigerVNC port
      targetPort: 1234 # Links straight onto the container socket
      nodePort: 1234  # Persistent physical port mapping across your LAN network
