apiVersion: v1
kind: ConfigMap
metadata:
  name: your-value
  namespace: your-namespace
data:
  sentinel.conf: |
    port 1234
    dir /tmp
    
    # Service Name: redis-grid
    sentinel monitor mymaster your-value.redis-grid.your-value.svc.cluster.local 1234 2
    
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 10000
    sentinel parallel-syncs mymaster 1
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
